Feature/simulated sensor cdar 158
usdot-fhwa-stol/carma-utils pull request #140
Opened 2023-08-07 21:09 UTC by davidgayman

# PR Details

## Description

Initial PR for folks to begin reviewing, not ready for release.

The SimulatedSensor acts as a wrapper to the CARLA Semantic Lidar Sensor, capturing the data and performing post-processing to generate a list of detected objects upon request.

The SimulatedSesnsor.get_detected_objects_in_frame() function presents the primary processing sequence. Calls to internal utility classes build DetectedObject's, representing the detected vulnerable road users. High-speed LIDAR data is collected into a DataCollector class running in a separate context which self-populates via a callback.

The processing sequence performs the following stages:
1. Truth state retrieval.
2. Prefilter by distance from sensor.
3. LIDAR hitpoint retrieval.
4. Occlusion determination using a fractional hitpoint coverage threshold scaling proportionally with the sensor-to-object distance.
5. Application of a generic noise model to the results.

Processing frames are understood to consist of one full LIDAR sensor rotation, and may include vertical scan elements.

Configurability is provided to the SimulatedSensor, utility functions computing prefiltering and occlusion threshold scaling, and the noise model. Furthermore the noise model is extensible.

## Related Jira Key

[CDAR-158](https://usdot-carma.atlassian.net/browse/CDAR-158)

## Motivation and Context

This new feature is provided to enable vulnerable road user detection using a LIDAR sensor in the context of a CARLA-driven simulation. The data is intended to feed into a CARMA V2X system for data fusion with other sensors and action by CARMA platform vehicles.

## How Has This Been Tested?

Code is being unit tested, and integration testing in test/integration/simulated_sensor_open3d_lidar.py successfully collects data into the internal DataCollector and performs cache rotation.

Further testing is required before release.

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [x ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [x ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-08-25 17:15 UTC, davidgayman commented
Ok ready for full review.

2023-08-28 19:46 UTC, MishkaMN requested changes

2023-08-28 20:17 UTC, MishkaMN requested changes

2023-08-28 20:17 UTC, MishkaMN commented on carma_utils/sensorlib/src/SemanticLidarSensor.py
> +        return dt_dr * range * t_nominal
From the way the object's size is being represented by the horizontal and vertical fov degrees from the sensor's perspective, I no longer think we need the adjusted threshold. The threshold can stay just a fractional (0;1]

2023-08-30 15:32 UTC, MishkaMN submitted a review, later dismissed

2023-08-30 15:34 UTC, willjohnsonk reviewed
No major comments to add, a minor one is that you may consider updating the copyright comment dates to 2023 unless there is a specific reason we're keeping 2021 that I'm unaware of

2023-08-30 17:55 UTC, paulbourelly999 commented on carma_utils/sensorlib/src/__init__.py
What are these files for?

2023-08-30 17:56 UTC, paulbourelly999 commented on carma_utils/sensorlib/src/collector/__init__.py
What are these files for?

2023-08-30 17:57 UTC, paulbourelly999 commented on carma_utils/sensorlib/test/doc/SensorTestCalculations.ods
What is this file for?

2023-09-05 14:00 UTC, MishkaMN commented on carma_utils/sensorlib/src/SemanticLidarSensor.py
> +        return (horizontal_fov / horizontal_angular_resolution) * (vertical_fov / vertical_angular_resolution)
yeah it is probably due to performance issue, but it is a configurable parameter, so we can change it during testing. For reference, it looks like 56k points_per_second was in the example of CARLA https://carla.readthedocs.io/en/latest/ref_sensors/

2023-09-05 18:39 UTC, willjohnsonk approved these changes
Looks good to me, if the unit tests on your end run without issue I think we can merge

2023-09-05 20:07 UTC, MishkaMN approved these changes

2023-09-05 20:07 UTC, merged