Fix average speed math error
usdot-fhwa-stol/carma-utils pull request #210
Opened 2024-01-08 22:21 UTC by MishkaMN

# PR Details
## Description

## Related GitHub Issue

## Related Jira Key

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the [**CONTRIBUTING**](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2024-01-09 16:42 UTC, paulbourelly999 commented
After talking more about this I think this fix should not be necessary. Negative Vf should only be an issue if you generate a position trajectory that has a non 0 initial velocity and a zero first delta d. The fix should be up stream components should generate a trajectory that has at least one step of delta d to account for the distance covered during acceleration. This will fix the negative signal. We should also log some kind of error for negative VIs and then I think it is OK to call max.

2024-01-10 22:38 UTC, adamlm requested changes
See individual comments. For some reason, they didn't associate with the review.

2024-01-10 22:47 UTC, MishkaMN commented on trajectory_utils/include/trajectory_utils/conversions/conversions.h
> +class negative_speed_from_conversion : public std::exception {
used runtime instead and removed the class

2024-01-10 22:50 UTC, MishkaMN commented on trajectory_utils/src/trajectory_utils/conversions/conversions.cpp
> +  double detected_nagative_speed = 0.0;
renamed

2024-01-10 22:50 UTC, MishkaMN commented on trajectory_utils_ros2/include/trajectory_utils/conversions/conversions.hpp
> +class negative_speed_from_conversion : public std::exception {
ditto

2024-01-10 22:50 UTC, MishkaMN commented on trajectory_utils_ros2/src/trajectory_utils/conversions/conversions.cpp
> +  double detected_nagative_speed = 0.0;
ditto

2024-01-11 14:00 UTC, adamlm approved these changes

2024-01-11 20:17 UTC, paulbourelly999 approved these changes
Looks good

2024-01-16 22:59 UTC, merged