Feature/add bsm helper
usdot-fhwa-stol/carma-utils pull request #86
Opened 2021-12-03 15:58 UTC by lewisid

# PR Details
## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [ ] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
[CARMA Contributing Guide](https://github.com/usdot-fhwa-stol/carma-platform/blob/develop/Contributing.md) 
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2021-12-06 14:50 UTC, msmcconnell requested changes

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/CMakeLists.txt
> +# Copyright (C) 2020-2021 LEIDOS.
Should just be 2021 since this file didn't exist in 2020

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/CMakeLists.txt
> +  roscpp
I don't see usage of roscpp or cav_msgs anywhere in this package. Please remove all references to unused dependencies.

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/include/bsm_helper/bsm_helper.h
> +             * @param id The incoming bsm id
can you add a bit of description about the encoding (how the input array needs to be structured)

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/src/bsm_helper.cpp
> +    std::string BSMHelper::bsmIDtoString(std::vector<uint8_t, std::allocator<uint8_t>> id)
Please add a size check to this method which verifies the input array has a length that fits within the requirements of a BSM. Throw an exception in this case.

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/src/bsm_helper.cpp
> +        int_id >> id_num;
Converting to a string and then pushing into a long just to convert back to a string seems pretty round about. Couldn't you just push each byte directly into the "unsigned long" using bit wise operators?

2021-12-06 14:50 UTC, msmcconnell commented on bsm_helper/CMakeLists.txt
> +# Copyright (C) 2020-2021 LEIDOS.
check all files

2021-12-06 14:55 UTC, msmcconnell commented on bsm_helper/include/bsm_helper/bsm_helper.h
> +#include <string>
Almost missed this,

You need to add a 
#pragma once 
to the top of this file as an include guard. 
Also all source code files though have the license comment

2021-12-06 19:41 UTC, msmcconnell requested changes

2021-12-06 19:41 UTC, msmcconnell commented on bsm_helper/src/bsm_helper.cpp
> +        if(id.size() > 4)
Should this be !=
Is a 3 element input valid?

2021-12-06 19:41 UTC, msmcconnell commented on bsm_helper/src/bsm_helper.cpp
> +          id_num = (id_num * pow(10, 2)) + id.at(i) ;
I think this method is prone to unit conversion errors. The pow function returns a double which means id_num might be upcast first which could result in a bit flip. At least that's what my intuition tells me. I thick bitwise operators are the better choice here

```
for(...)
{
   id_num = (id_num << 8) | id.at(i);
}
```

See
https://www.geeksforgeeks.org/bitwise-operators-in-c-cpp/

2021-12-07 14:58 UTC, dan-du-car approved these changes

2021-12-07 15:24 UTC, msmcconnell requested changes

2021-12-07 15:24 UTC, msmcconnell commented on bsm_helper/src/bsm_helper.cpp
> +            std::cout<< std::hex << static_cast<int>(id.at(i)) << std::endl;
These prints should either be removed or made into ros debug prints

2021-12-07 18:04 UTC, msmcconnell approved these changes

2021-12-07 18:04 UTC, merged